import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "online kinnus",
  description: "Generated by create next app",
  keywords: "E-commerce, online shopping",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
