import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "online kinnus",
  description: "Generated by create next app",
  keywords: "E-commerce, online shopping",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}

        <footer className="mt-5 bg-amber-500 text-black text-center">
          2025. All rights reserved
        </footer>
      </body>
    </html>
  );
}
